[package]
name = "parcel"
version = "0.1.0"
authors = ["oskarbraten <oskarbraten@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bincode = "1.3.1"
serde = { version = "1.0.123", features = ["derive", , "serde-serialize"] }